sulu_admin:
    email: "%env(SULU_ADMIN_EMAIL)%"
    forms:
        directories:
            - "%kernel.project_dir%/config/forms"
    lists:
        directories:
            - "%kernel.project_dir%/config/lists"
    resources:
        programmers:
            routes:
                list: app.get_programmers_list
                detail: app.get_programmers

    # Registering Selection Field Types in this section
    field_type_options:
        selection:
            programmers_selection:
                default_type: list_overlay
                resource_key: programmers
                types:
                    list_overlay:
                        adapter: table
                        list_key: programmers
                        display_properties:
                            - title
                        icon: fa-calendar
                        label: 'app.programmers'
                        overlay_title: 'app.programmers'
